// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puhivubmtgddojiiezwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1aGl2dWJtdGdkZG9qaWllendsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDYxNTYsImV4cCI6MjA3MDQ4MjE1Nn0.qF1tPayiFkCel_E0YvzbhSVokaABzmxHRhMYzN9pXis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});